#开发环境
spring:

  datasource:
    druid:

      one:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.48.129:3306/springbootv2?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: root
        password: Fernandes.18
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        initial-size: 5
        filters: stat,wall
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      two:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.48.129:3306/springbootv3?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: root
        password: Fernandes.18
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        initial-size: 5
        filters: stat,wall
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500